Fix/v9
concrete5japan/theme_palette pull request #1
Opened 2024-11-29 08:30 UTC by MOYORi

@hissy 

確認お願いします

2024-11-29 08:42 UTC, hissy requested changes
@MOYORi 

ありがとうございます。いくつか対応お願いします。

2024-11-29 08:42 UTC, hissy commented on blocks/google_map/templates/palette_map/view.php
> +$unique_identifier = '';
@MOYORi 

この変数をここで初期化してしまうと、どんな場合でも空文字になってしまい、意味がなくなってしまいます。
そもそもこのあと何のために使われている変数ですか？

2024-11-29 08:42 UTC, hissy commented on blocks/image/templates/add_title/view.php
> +    $imageTag->addClass('ccm-image-block img-fluid bID-' . $bID);
@MOYORi 

class 名が img-responsive から img-fluid に変わってますが、大丈夫ですか？
テーマ側のCSSに img-responsive の記述があったら、この変更のせいでデザインが変わってしまうと思います。

2024-11-29 08:42 UTC, hissy commented on blocks/image_slider/templates/slick_carousel/view.php
> +                            if ($row['title']) {
@MOYORi 

元々のコードでは setAttribute はなかったと思いますが、何で追加したのか教えてもらえますか？

2024-11-29 08:42 UTC, hissy commented on themes/palette/inc/header.php
> +        <?php Loader::element('header_required', array('pageTitle' => isset($pageTitle) ? $pageTitle : ''));?>
@MOYORi 

コアの最新のテーマのように、 pageDescription と pageMetaKeywords もパラメーターで header_required に渡すように変えてください。というか、コアの該当部分を取ってくるだけで良いです。

https://github.com/concretecms/concretecms/blob/9.3.x/concrete/themes/elemental/elements/header_top.php

Stucco の方では気づかなかったので、Stuccoでもこのheader_requiredの読み込みコードが古かったら、同じように更新してください。

2024-12-02 07:05 UTC, MOYORi commented on blocks/image_slider/templates/slick_carousel/view.php
> +                            if ($row['title']) {
コアにsetAttributeがあったので追加しました。
不要であれば削除します

2024-12-02 07:07 UTC, MOYORi commented on blocks/image/templates/add_title/view.php
> +    $imageTag->addClass('ccm-image-block img-fluid bID-' . $bID);
@hissy 

bootstrap.cssで img-responsiveが使われていたので戻しておきます

2024-12-02 07:11 UTC, MOYORi commented on blocks/google_map/templates/palette_map/view.php
> +$unique_identifier = '';
@hissy 

`$unique_identifier = $unique_identifier ?? '';
`
これにしたら良いでしょうか？
同じページに複数google_mapブロックを入れた際に使用されるものかと思っていましたが、複数入れてみたところ特に `id="googleMapCanvas<?php echo $unique_identifier?>"` が変わらなかったです。scriptタグ部分にも$unique_identifierが使用されているのでブロックIDが入るようにした方が良いでしょうか？

2024-12-02 08:08 UTC, hissy commented on blocks/image_slider/templates/slick_carousel/view.php
> +                            if ($row['title']) {
@MOYORi 

なるほど、コアに追随するためですね。理解しました。これはこのままでOKです。

2024-12-02 08:10 UTC, hissy commented on blocks/google_map/templates/palette_map/view.php
> +$unique_identifier = '';
@MOYORi 

`$unique_identifier = $unique_identifier ?? '';` の方がまだ無意味ではないですが、何も入らないなら結局意味がないですね。
提案してもらったように、 `$bID` にした方が良さそうです。

2024-12-02 08:52 UTC, MOYORi commented
@hissy 

指摘いただいた点を修正しました。
確認お願いします

2024-12-28 13:28 UTC, merged